# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tirefi.re
email: tirefire@tirefi.re
description: > # Tires are not prone to self-ignition as a tire must be heated to at least 400 °C (750 °F) for a period of several minutes prior to ignition.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tirefi.re" # the base hostname & protocol for your site
twitter_username: tirefirebot
github_username:  tirefire

emptyArray: []

# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      webring: true

# Build settings
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
google_analytics_tracking_id: UA-79918240-1
